namespace Clair.TextEditor.RazorLib.Decorations.Models;

public class GenericDecorationMapper : IDecorationMapper
{
    public string Map(byte decorationByte)
    {
        var decoration = (GenericDecorationKind)decorationByte;

        return decoration switch
        {
            GenericDecorationKind.None => string.Empty,
            GenericDecorationKind.Keyword => "di0",
            GenericDecorationKind.KeywordControl => "di4",
            GenericDecorationKind.EscapeCharacterPrimary => "di7",
            GenericDecorationKind.EscapeCharacterSecondary => "di7 di8",
            GenericDecorationKind.StringLiteral => "di6",
            GenericDecorationKind.Variable => "di1",
            GenericDecorationKind.CommentSingleLine => "di5",
            GenericDecorationKind.CommentMultiLine => "di5",
            GenericDecorationKind.Function => "di3",
            GenericDecorationKind.PreprocessorDirective => "di9",
            GenericDecorationKind.DeliminationExtended => "di6",
            GenericDecorationKind.Type => "di2",
            ///
            GenericDecorationKind.Css_Identifier => "ci_css-identifier",
            GenericDecorationKind.Css_PropertyName => "ci_css-property-name",
            GenericDecorationKind.Css_PropertyValue => "ci_css-property-value",
            GenericDecorationKind.Css_Comment => "ci_comment",
            GenericDecorationKind.Css_Function => "ci_method",
            ///
            GenericDecorationKind.Json_PropertyKey => "ci_json-property-key",
            GenericDecorationKind.Json_String => "ci_string",
            GenericDecorationKind.Json_Number => "ci_te_number",
            GenericDecorationKind.Json_Integer => "ci_te_integer",
            GenericDecorationKind.Json_Keyword => "ci_keyword",
            GenericDecorationKind.Json_LineComment => "ci_comment",
            GenericDecorationKind.Json_BlockComment => "ci_comment",
            GenericDecorationKind.Json_Null => string.Empty,
            GenericDecorationKind.Json_Document => string.Empty,
            GenericDecorationKind.Json_Error => string.Empty,
            ///
            GenericDecorationKind.Xml_AttributeName => "ci_attribute-name",
            GenericDecorationKind.Xml_AttributeValue => "ci_attribute-value",
            GenericDecorationKind.Xml_AttributeOperator => "ci_attribute-value",
            GenericDecorationKind.Xml_AttributeDelimiter => "ci_attribute-value",
            GenericDecorationKind.Xml_TagNameNone => "ci_tag-name",
            GenericDecorationKind.Xml_TagNameOpen => "ci_tag-name",
            GenericDecorationKind.Xml_TagNameClose => "ci_tag-name",
            GenericDecorationKind.Xml_TagNameSelf => "ci_tag-name",
            GenericDecorationKind.Xml_Comment => "ci_comment",
            GenericDecorationKind.Xml_CustomTagName => "ci_te_custom-tag-name",
            GenericDecorationKind.Xml_EntityReference => "ci_te_entity-reference",
            GenericDecorationKind.Xml_HtmlCode => "ci_te_html-code",
            GenericDecorationKind.Xml_InjectedLanguageFragment => "ci_injected-language-fragment",
            GenericDecorationKind.Xml_InjectedLanguageComponent => "ci_injected-language-component",
            GenericDecorationKind.Xml_Error => "ci_te_error",
            GenericDecorationKind.Xml_InjectedLanguageCodeBlock => "ci_te_injected-language-code-block",
            GenericDecorationKind.Xml_InjectedLanguageCodeBlockTag => "ci_te_injected-language-code-block-tag",
            GenericDecorationKind.Xml_InjectedLanguageKeyword => "ci_keyword",
            GenericDecorationKind.Xml_InjectedLanguageTagHelperAttribute => "ci_te_injected-language-tag-helper-attribute",
            GenericDecorationKind.Xml_InjectedLanguageTagHelperElement => "ci_te_injected-language-tag-helper-element",
            GenericDecorationKind.Xml_InjectedLanguageMethod => "ci_method",
            GenericDecorationKind.Xml_InjectedLanguageVariable => "ci_variable",
            GenericDecorationKind.Xml_InjectedLanguageType => "ci_type",
            GenericDecorationKind.Xml_InjectedLanguageStringLiteral => "ci_string",
            ///
            GenericDecorationKind.Razor_AttributeName => "ci_attribute-name",
            GenericDecorationKind.Razor_AttributeValue => "ci_attribute-value",
            GenericDecorationKind.Razor_AttributeOperator => "ci_attribute-value",
            GenericDecorationKind.Razor_AttributeDelimiter => "ci_attribute-value",
            GenericDecorationKind.Razor_AttributeNameInjectedLanguageFragment => "ci_injected-language-fragment",
            GenericDecorationKind.Razor_AttributeValueInjectedLanguageFragment => "ci_injected-language-fragment",
            GenericDecorationKind.Razor_AttributeValueInterpolationStart => "ci_attribute-value",
            GenericDecorationKind.Razor_AttributeValueInterpolationContinue => "ci_attribute-value",
            GenericDecorationKind.Razor_TagNameNone => "ci_tag-name",
            GenericDecorationKind.Razor_TagNameOpen => "ci_tag-name",
            GenericDecorationKind.Razor_TagNameClose => "ci_tag-name",
            GenericDecorationKind.Razor_TagNameSelf => "ci_tag-name",
            GenericDecorationKind.Razor_Comment => "ci_comment",
            GenericDecorationKind.Razor_CustomTagName => "ci_te_custom-tag-name",
            GenericDecorationKind.Razor_EntityReference => "ci_te_entity-reference",
            GenericDecorationKind.Razor_HtmlCode => "ci_te_html-code",
            GenericDecorationKind.Razor_InjectedLanguageFragment => "ci_injected-language-fragment",
            GenericDecorationKind.Razor_InjectedLanguageComponent => "ci_injected-language-component",
            GenericDecorationKind.Razor_CSharpMarker => "ci_type",
            GenericDecorationKind.Razor_Error => "ci_te_error",
            GenericDecorationKind.Razor_InjectedLanguageCodeBlock => "ci_te_injected-language-code-block",
            GenericDecorationKind.Razor_InjectedLanguageCodeBlockTag => "ci_te_injected-language-code-block-tag",
            GenericDecorationKind.Razor_InjectedLanguageKeyword => "ci_keyword",
            GenericDecorationKind.Razor_InjectedLanguageTagHelperAttribute => "ci_te_injected-language-tag-helper-attribute",
            GenericDecorationKind.Razor_InjectedLanguageTagHelperElement => "ci_te_injected-language-tag-helper-element",
            GenericDecorationKind.Razor_InjectedLanguageMethod => "ci_method",
            GenericDecorationKind.Razor_InjectedLanguageVariable => "ci_variable",
            GenericDecorationKind.Razor_InjectedLanguageType => "ci_type",
            GenericDecorationKind.Razor_InjectedLanguageStringLiteral => "ci_string",
            ///
            GenericDecorationKind.Terminal_Comment => "ci_comment",
            GenericDecorationKind.Terminal_Keyword => "ci_keyword",
            GenericDecorationKind.Terminal_StringLiteral => "ci_string",
            GenericDecorationKind.Terminal_TargetFilePath => "ci_type",
            GenericDecorationKind.Terminal_Error => "ci_tree-view-exception",
            GenericDecorationKind.Terminal_Warning => "ci_tree-view-warning",
            ///
            _ => string.Empty,
        };
    }
}
